### ISSUE TITLE
Tests in Github Actions Fail with ReadTheDocs Theme Update

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#14]
@PeterSulcs pushing my changes to update to readthedocs theme caused the tests in github actions to fail.. any ideas?

**Comment by PeterSulcs** [comment]
The issue is the change to the field for the download link. The mock tests expect a key that is now `DownloadLink`. I don't think the sphinx change had any impact. This a good example of when having a large scope of changes for a Pull Request is sometimes problematic and confusing.

**Comment by PeterSulcs** [comment]
You can see the actual error here https://github.com/PHM-Data-Hub/lib/runs/2240837933?check_suite_focus=true

**Comment by PeterSulcs** [comment]
This should also fail locally. Does running `pytest` reproduce the issue on your machine?

**Comment by cbarnes7** [comment]
this issue was because matt/jiwoo changed the json to account for nested dataset download urls and I didn't realize. I just updated the CLI to work with this as seen in #15. Running pytest still fails locally for me with that old "no module machine_data_hub" error that's being caused I think you said from a conda conflict or something? Anyway could you run this locally and see if it passes pytest locally for you?

**Comment by PeterSulcs** [comment]
Push your changes to a branch and let the github actions pipeline run there, once they are passing merge to main. FWIW, that local issue should be resolved if you just run `poetry shell` before running pytest

**Comment by cbarnes7** [comment]
@PeterSulcs how do I access the documentation hosted on readthedocs?

**Comment by PeterSulcs** [comment]
Click on the badge in GitHub readme

**Comment by PeterSulcs** [comment]
https://machine-data-hub.readthedocs.io/en/latest/?badge=latest
