### ISSUE TITLE
Data Types

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#16]
@PeterSulcs Datatypes of datasets we currently have (copied from excel file):

xlsx | 3
NNA | 2
csv | 18
mat | 31
txt | 4
csv, mat | 2
dat | 1
raw text | 5

**Comment by PeterSulcs** [comment]
1. What is `NNA`?
2. Is `dat` actually a text file just with a fancy file extension?

**Comment by cbarnes7** [comment]
@pjw901015 add links to datasets that are NNA and dat

**Comment by PeterSulcs** [comment]
Steel plates:
```
      "http://archive.ics.uci.edu/ml/machine-learning-databases/00198/Faults.NNA",
      "http://archive.ics.uci.edu/ml/machine-learning-databases/00198/Faults27x7_var"
```
