### ISSUE TITLE
'Contains nonstandard whitespace'

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#25]
@PeterSulcs most recent push to formatting branch failed testing. I've been looking into documentation but I'm having trouble.

```
def test_success_download(runner, mock_get_datasets, mock_requests_file_get):
        #print(f"Try the get_datasets() mock: {machine_data_hub.cli.get_datasets('hello')}")
        #print(f"Try the request.get mock: {requests.get('hello').json()}")
        result = runner.invoke(app, ["download", "1", "1"])
>       assert result.exit_code == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Result ValueError(<MagicMock name='get().headers.get()' id='140512993898896'>, 'Contains nonstandard whitespace')>.exit_code

tests/test_cli.py:79: AssertionError
```

Let me know if you have any ideas. `headers.get()` is only used in this line of code for the progress bar `total_size_in_bytes = int(r.headers.get('content-length', 0))`

**Comment by PeterSulcs** [comment]
I think the change to streaming files requires a more elaborate mock. I will take a look to see what makes the most sense right now.

**Comment by PeterSulcs** [comment]
@cbarnes7 please consider merging my pull request into your formatting branch. https://github.com/machine-data-hub/lib/pull/26
