### ISSUE TITLE
SOS the updated JSON request is failing

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#29]
<img width="875" alt="Screen Shot 2021-05-25 at 4 25 51 PM" src="https://user-images.githubusercontent.com/40673866/119580797-ff7ae700-bd75-11eb-8e8e-768a292dc807.png">

@PeterSulcs When matt pushed the changes with the updated JSON, now the request is failing. I think it has to do with JSON formatting? https://machinedatahub.ai/datasets.json

**Comment by PeterSulcs** [comment]
I think the JSON hosted in the web app is malformed. I would recommend pasting into an editor that can lint JSON and have it tell you what is wrong with it.

**Comment by PeterSulcs** [comment]
VSCode can do this

**Comment by PeterSulcs** [comment]
Based on the error you can probably just inspect line 1334 and you'll see something

**Comment by PeterSulcs** [comment]
Confirmed... @mattsul  There is residual leftover from a merge conflict. I believe you only want what is above the `======` and can delete the rest and redeploy the web app.
