### ISSUE TITLE
Mock requests.get is causing failed pytest

### ISSUE THREAD

**Issue by cbarnes7** [machine-data-hub/lib#8]
<img width="1056" alt="Screen Shot 2021-02-23 at 9 19 42 AM" src="https://user-images.githubusercontent.com/40673866/108881539-44954e80-75b8-11eb-912b-f0f3942cb92f.png">

@PeterSulcs 

I followed the tutorial for hypermodern for mocking requests, but instead of `result = runner.invoke(console.main)` in my tests, I used `result = runner.invoke(app, ["download", "Combined Cycle Power Plant Data Set"])` as seen from this Typer testing tutorial https://typer.tiangolo.com/tutorial/testing/

When I run the code with the mock for requests.get with the hypermodern python tutorial code, it works fine. Im not sure how to resolve this issue, and also not sure if I should spend significant time on it if we will be migrating to PostGres anyway? Let me know

**Comment by PeterSulcs** [comment]
I will clone and try to reproduce on my side, and provide my recommendation. Hopefully tonight.

**Comment by PeterSulcs** [comment]
@cbarnes7 I'll take a deeper look later, but I don't think you should have to include `src.` when you import the app. Because the tests assume the package is installed (good), and there is no `__init__.py` in `src` (also good), I wouldn't expect src to be recognized by python as a module. Please try removing `src.` from the import line.

**Comment by cbarnes7** [comment]
@PeterSulcs Still getting the same error after removing src

**Comment by cbarnes7** [comment]
@PeterSulcs when running nox on your latest commit, I am getting the error 
```
tests/test_cli.py:9: in <module>
    import phm_data_hub
E   ModuleNotFoundError: No module named 'phm_data_hub'
```
I believe this error is why I previously had src.phm_data_hub ? No error when running `poetry run pytest` or `poetry run pytest --cov=tests`

**Comment by cbarnes7** [comment]
<img width="887" alt="Screen Shot 2021-03-02 at 10 41 14 PM" src="https://user-images.githubusercontent.com/40673866/109764440-668a6480-7ba8-11eb-8b14-2a73299ed866.png">
@PeterSulcs my latest run with nox even after your testing fixes still gives me this error. I haven't resolved the other pytest warning, you think this could also be a result of anaconda clashing with this still?

**Comment by PeterSulcs** [comment]
Yes. I think it is related to how the nox package is installed in your
environment. I wouldn't stress too much about making it run locally, if you
can get nox running in github actions that is perfectly fine.

As long as pytest runs locally you can let the multiple python version test
happen in the pipeline.
